export const UI_TEXT = {
  COMMON: {
    LOADING: "Cargando...",
    SAVE: "Guardar",
    CANCEL: "Cancelar",
    DELETE: "Eliminar",
    EDIT: "Editar",
    VIEW: "Ver",
    SEARCH: "Buscar",
    ACTIONS: "Acciones",
  },
  DATA_TABLE: {
    EMPTY_MESSAGE: "No hay datos disponibles",
    SEARCH_PLACEHOLDER: "Buscar...",
    LOADING: "Cargando...",
  },
  MODAL: {
    CONFIRM_TEXT: "Confirmar",
    CANCEL_TEXT: "Cancelar",
    PROCESSING: "Procesando...",
  },
  SIDEBAR: {
    BRAND_NAME: "ZULIM",
    BRAND_SUBTITLE: "Sistema ERP",
    NAV_ITEMS: {
      DASHBOARD: "Inicio",
      POS: "Punto de Venta",
      PRODUCTS: "Productos",
      SALES: "Ventas",
      CLIENTS: "Clientes",
      REPORTS: "Reportes",
      USERS: "Usuarios",
    },
    LOGOUT: "Cerrar Sesión",
    USER_DEFAULT: "Usuario",
  },
  ROLES: {
    ADMIN: "Administrador",
    SELLER: "Vendedor",
  },
  POS_COMPONENTS: {
    CART: {
      EMPTY_TITLE: "Carrito vacío",
      EMPTY_SUBTITLE: "Agrega productos para comenzar",
      QUANTITY: "Cantidad",
      SUBTOTAL: "Subtotal",
      REMOVE_BUTTON: "Eliminar",
    },
    PRODUCT_SEARCH: {
      PLACEHOLDER: "Buscar producto por nombre o SKU...",
      NO_RESULTS: "No se encontraron productos",
      SKU_LABEL: "SKU:",
      STOCK_LABEL: "Stock:",
    },
    SEARCH: {
      PLACEHOLDER: "Buscar producto por nombre o SKU...",
      SKU_LABEL: "SKU:",
      STOCK_LABEL: "Stock:",
    },
    ROUNDED_TOTAL: {
      SUBTOTAL: "Subtotal",
      ROUNDED: "Redondeado",
      TOTAL: "Total a Cobrar",
      ROUNDING: "Redondeo",
    },
  },
  TABLE: {
    COLUMNS: {
      SKU: "SKU",
      PRODUCT: "Producto",
      UNIT: "Unidad",
      STOCK: "Stock",
      COST: "Costo",
      SALE: "Venta",
      MARGIN: "Margen",
      ID: "ID",
      DATE: "Fecha",
      CLIENT: "Cliente",
      METHOD: "Método",
      SUBTOTAL: "Subtotal",
      TOTAL: "Total",
      TYPE: "Tipo",
    },
  },
  STATS: {
    TOTAL: "Total",
    LOW_STOCK: "Stock Bajo",
    OUT_OF_STOCK: "Sin Stock",
    TOTAL_VALUE: "Valor Total",
    SALES_TODAY: "Ventas Hoy",
    NO_SALES: "Sin ventas",
    TOTAL_PRODUCTS: "Total Productos",
    ACTIVE_CLIENTS: "Clientes Activos",
    PRODUCTS: "Productos",
    IN_CATALOG: "En catálogo",
    CLIENTS: "Clientes",
    REGISTERED: "Registrados",
    LOW_STOCK_COUNT: "Productos con stock bajo",
    SALES_TODAY_CARD: "Ventas Hoy",
    TOTAL_DAY: "Total del Día",
    AVERAGE_TICKET: "Ticket Promedio",
  },
  REPORTS_LIST: {
    SALES_PERIOD: {
      TITLE: "Ventas por Período",
      DESCRIPTION: "Análisis de ventas por día, semana o mes",
    },
    PRICE_EVOLUTION: {
      TITLE: "Evolución de Precios",
      DESCRIPTION: "Historial de cambios de precios e inflación",
    },
    PROFIT_MARGINS: {
      TITLE: "Márgenes de Ganancia",
      DESCRIPTION: "Rentabilidad por producto y categoría",
    },
    STOCK_ROTATION: {
      TITLE: "Rotación de Stock",
      DESCRIPTION: "Productos más y menos vendidos",
    },
    CLIENTS_AFIP: {
      TITLE: "Clientes y AFIP",
      DESCRIPTION: "Facturación por condición fiscal",
    },
    CASH_REGISTER: {
      TITLE: "Caja Diaria",
      DESCRIPTION: "Movimientos de efectivo y medios de pago",
    },
  },
  GREETINGS: {
    MORNING: "Buenos días",
    AFTERNOON: "Buenas tardes",
    EVENING: "Buenas noches",
  },
  QUICK_ACTIONS: {
    TITLE: "Acciones Rápidas",
    NEW_SALE: "Nueva Venta",
    PRODUCTS: "Productos",
    REPORTS: "Reportes",
    CLIENTS: "Clientes",
  },
  SYSTEM_STATUS: {
    TITLE: "Estado del Sistema",
    DATABASE: "Base de Datos",
    CONNECTED: "Conectado",
    AFIP: "AFIP",
    ACTIVE: "Activo",
    SYNC: "Sincronización",
    PENDING: "Pendiente",
  },
  PAGES: {
    DASHBOARD: {
      WELCOME: "Bienvenido al sistema de gestión",
    },
    POS: {
      TITLE: "Punto de Venta",
      SUBTITLE: "Sistema de ventas rápido",
      SEARCH_PRODUCT: "Buscar Producto",
      CART: "Carrito",
      ITEMS_COUNT: "productos",
      SUMMARY: "Resumen",
      CHARGE_BUTTON: "Cobrar",
      CLEAR_CART: "Limpiar Carrito",
      KEYBOARD_SHORTCUTS: "Atajos de Teclado",
      SHORTCUTS: {
        SEARCH: "Buscar producto",
        SELECT: "Seleccionar",
        CANCEL: "Cancelar",
      },
    },
    PRODUCTS: {
      TITLE: "Productos",
      SUBTITLE: "Gestión de catálogo de productos",
      SEARCH_PLACEHOLDER: "Buscar por nombre o SKU...",
      EMPTY_MESSAGE: "No hay productos registrados",
      NEW_BUTTON: "Nuevo Producto",
      IMPORT_EXCEL: "Importar Excel",
      EXPORT_EXCEL: "Exportar Excel",
    },
    REPORTS: {
      TITLE: "Reportes",
      SUBTITLE: "Análisis y reportes del negocio",
    },
    SALES: {
      TITLE: "Ventas",
      SUBTITLE: "Historial de transacciones",
      SEARCH_PLACEHOLDER: "Buscar por ID o cliente...",
      EMPTY_MESSAGE: "No hay ventas registradas",
      RECENT_SALES: "Últimas Ventas",
      VIEW_ALL: "Ver todas",
      NO_SALES_TODAY: "No hay ventas registradas hoy",
      FIRST_SALE_BUTTON: "Realizar primera venta",
    },
    LOGIN: {
      TITLE: "ZULIM",
      SUBTITLE: "Sistema de Gestión Empresarial",
      EMAIL_LABEL: "Email",
      EMAIL_PLACEHOLDER: "tu@email.com",
      PASSWORD_LABEL: "Contraseña",
      PASSWORD_PLACEHOLDER: "••••••••",
      LOGIN_BUTTON: "Iniciar Sesión",
      LOGGING_IN: "Iniciando sesión...",
      ERROR: "Credenciales inválidas",
      TEST_CREDENTIALS: "Credenciales de prueba:",
      TEST_CREDENTIALS_VALUE: "admin@zulim.com / admin123",
    },
  },
} as const;
